### ISSUE TITLE
Question about inference error?

### ISSUE THREAD

**Issue by rockywind** [saic-vul/imvoxelnet#15]
The script is below.
`python tools/test.py --config configs/imvoxelnet/imvoxelnet_kitti.py --checkpoint work_dirs/imvoxelnet_kitti/kitti_ori.pth --show-dir work_dirs/imvoxelnet_kitti
`
The error is below.
`Traceback (most recent call last):
  File "tools/test.py", line 160, in <module>
    main()
  File "tools/test.py", line 111, in main
    dataset = build_dataset(cfg.data.test)
  File "/newnfs/zzwu/08_3d_code/imvoxelnet02/mmdetection3d/mmdet3d/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/CN/zizhang.wu/anaconda3/envs/imvoxelnet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'KittiMultiViewDataset is not in the dataset registry'
`

**Comment by filaPro** [comment]
Hi @rockywind ,
`KittiMultiViewDataset` is for sure registered in this [line](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/kitti_monocular_dataset.py#L9). This dataset is implemented only in `imvoxelnet` codebase. According to your traceback you are using original registry from `mmdetection3d/mmdet3d` (/newnfs/zzwu/08_3d_code/imvoxelnet02/mmdetection3d/mmdet3d) instead of `imvoxelnet/mmdet3d`. So I think this `mmdetection3d` folder is a consequence of inaccurate installation.

**Comment by rockywind** [comment]
Thanks a lot! @filaPro
